@RevitFlow.API_HostAddress = http://localhost:5147

GET {{RevitFlow.API_HostAddress}}/health/db
Accept: application/json

###

GET {{RevitFlow.API_HostAddress}}/projects
Accept: application/json

###

POST {{RevitFlow.API_HostAddress}}/projects
Content-Type: application/json

{
  "projectName": "Sample"
}

###
